services:
  - type: web
    name: eld-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
    buildFilter:
      paths: ["backend/**"]
    rootDir: backend
